### PR TITLE
fix:(frontend): improve auto-scroll functionality

### PR DESCRIPTION
**Pull request by Aardenfell**
- Made some changes to `HomePage.tsx` and `MessageViewer.tsx` that I hope allow for continuous scrolling when the AI is responding. I wasn't able to fully retest them after the https://github.com/pinacai/PINAC_Workspace/commit/07c6bc73bee214ae043ecd5064dc809084591200 commit because it stops any further submissions until the AI responds, which is always in my case.
- Feel free to try my changes out and revert them if they flat out don't work.

### CODE REVIEW

**Comment by RajeshTechForge** [comment]
Ok, let me check it after merging, because the app is not running on GitHub Codespace for some reason .

I will inform you after checking.

**Comment by Aardenfell** [comment]
okay, thanks.

**Comment by DevanshArora312** [comment]
I think the scroll issue still persists, maybe only on my local machine it may not be working, but if the issue is persistent, you can try creating a dummy div and observing it using Intersection Observer Web API, and then implement smooth scrolling to the dummy div placed at the bottom of messages.

**Comment by Aardenfell** [comment]
I'll try that next time I get to my machine. I'll also look into finding a method to generate dummy responses so I can test my changes before making a PR

**Comment by RajeshTechForge** [comment]
As you know python, setup PINAC-Nexus in your machine. You just need OpenAI or Google Gemini key.

**Comment by Aardenfell** [comment]
> As you know python, setup PINAC-Nexus in your machine. You just need OpenAI or Google Gemini key.

I'll do just that. I didn't even notice that this was available. Is it plug n play or do I need some additional tweaking?

**Comment by RajeshTechForge** [comment]
Wait a while, I will update it's Readme

**Comment by RajeshTechForge** [comment]
hello @Aardenfell, I have completed its Readme, check out the details there.

**Comment by Aardenfell** [comment]
oh dang he beat me to it

**Pull request merged**
