### PR TITLE
Feature/issue 14/chatbox automatic scrolling

### PR DESCRIPTION
**Pull request by Aardenfell**
Made some changes to `HomePage.tsx` and `MessageViewer.tsx` that I hope allow for continuous scrolling when the AI is responding.

### CODE REVIEW

**Comment by Aardenfell** [comment]
closing to pull changes first. Hadn't seen the updates.

**Comment by RajeshTechForge** [comment]
> closing to pull changes first. Hadn't seen the updates.

Is there any problem ?

**Comment by Aardenfell** [comment]
no, i just hadnt seen the latest commits, so im pulling those and retrying my changes.

**Comment by RajeshTechForge** [comment]
> no, i just hadnt seen the latest commits, so im pulling those and retrying my changes.

Oo, sure

**Pull request closed without merging**
