### PR TITLE
Made About Page Responsive

### LINKED ISSUE #56: Make the About Page Responsive
## Description

We always make sure our app is responsive for any screen size, but we have observed that the About Page is not that responsive in different screen heights. 

I’m looking for contributors eager to solve this bug. If you’re interested or have any questions, just knock me!

**Screenshort**:
Screenshot from 2024-07-08 21-37-37

### PR DESCRIPTION
**Pull request by CamTheWebGuy**
This change resolves #56 by making about page responsive.

### CODE REVIEW

**Review by RajeshTechForge — CHANGES_REQUESTED** [review]
Hello, @CamTheWebGuy! Unfortunately, these changes still don't meet the required responsiveness. In the video below, you can observe the unwanted scrolling behavior on this page. Pay attention to the difference between scrolling in the settings and scrolling on this specific page.

[Screenrecord](https://github.com/pinacai/PINAC_Workspace/assets/78198704/6f416b97-d12a-46f3-a615-623ac55cc7f8)

**Comment by CamTheWebGuy** [comment]
Roger Roger. I'll take a look.

**Comment by CamTheWebGuy** [comment]
@RajeshTechForge Updated.

**Review by RajeshTechForge — APPROVED** [review]
**Hello @CamTheWebGuy**,

Thanks for solving this responsive bug in the App UI. Your efforts in resolving this issue have significantly improved the user experience of our app. Looking for future contribution.

Warm regards,
**Rajesh Mondal**

**Pull request merged**
