### PR TITLE
added loader component and corresponding CSS

### PR DESCRIPTION
**Pull request by DevanshArora312**
1. Created a Loader message Component for post query processing.
2. Did not add any 3rd party package for creating the loader, made purely using CSS.
3. Loader component is housed in `MessageViewer.tsx` file with a structure similar to `AiMessage` component.

### CODE REVIEW

**Comment by RajeshTechForge** [comment]
Hello @DevanshArora312 ,

I wanted to express my gratitude for your recent contribution to PINAC Workspace. The implementation of animation loader has significantly enhanced our project’s usability and user experience. 🌟

Thanks again,
Rajesh Mondal

**Comment by DevanshArora312** [comment]
It was a fun and insightful experience for me as well as it was my first time contributing open-source. I hope to be able to contribute more to your wonderful project. 
Thanks.

(On a completely different note, while working on the previous issue , I seemed to have come across an Issue where when the AI model replies all the previous messages also get changed to the latest one, if the issue is persistent on your side too, then I'll be more than happy to try and contribute to fix that issue as well)

**Comment by RajeshTechForge** [comment]
That's amazing and let me check if this issue exists on my side also.

And don't forget to start this repo

**Comment by RajeshTechForge** [comment]
Hello @DevanshArora312 , I found the same issue on my side. I would like to assign you this issue, open a GitHub issue for it and start fixing it.
Happy coding!

**Comment by DevanshArora312** [comment]
Thanks @RajeshTechForge for confirming, I'll be creating the Issue ticket shortly. In the meantime , I have created a fix for typing animation enhancement Issue and will be creating a PR soon. Do check it if it meets your expectations.

**Pull request merged**
