### PR TITLE
feat(chatbox): implement automatic scrolling during AI response

### LINKED ISSUE #14: Implement Automatic Scrolling to Bottom in Chatbox During AI Response Generation
## Description

I’ve noticed something that could really smooth out our user experience. When our AI is crafting a response, it would be super helpful if the chatbox could automatically scroll to the bottom. This way, users can see the AI’s reply as it’s being written without having to manually scroll down.

It’s a small tweak, but I think it’ll make a big difference in keeping our chats flowing nicely. Plus, it adds that extra touch of polish that shows we care about the little details.

I’m on the lookout for enthusiastic contributors eager to tackle this enhancement. If you’re interested or have any questions, don’t hesitate to reach out to me!

### PR DESCRIPTION
**Pull request by Aardenfell**
- Added chatbox scrolling functionality.

Closes #14

### CODE REVIEW

**Comment by Aardenfell** [comment]
Something to note: 
I was unable to verify continuous scrolling with long AI responses due to the inability to test the AI behaviour in my environment.

**Comment by RajeshTechForge** [comment]
> Something to note: I was unable to verify continuous scrolling with long AI responses due to the inability to test the AI behaviour in my environment.

That's fine, I will check it.

**Review by RajeshTechForge — APPROVED** [review]

**Comment by RajeshTechForge** [comment]
**Hi @Aardenfell**,

Thanks for you contribution to our project. I want to let you know that your codes are functioning smoothly. Here is the video:
[Screencast from 2024-06-12 15-49-20.webm](https://github.com/pinacai/PINAC_Workspace/assets/78198704/41c210ba-7964-4c0d-9e2e-da3aee5a7740)

Here you can see it's showing user input by auto scrolling, which is great. Would you like add a contineous scrolling for ai response bubble with the auto-typing ?

Best,
**Rajesh Mondal**

**Comment by Aardenfell** [comment]
Ahh, that's what I was afraid of happening. Let me see if I can make it also scroll when the response bubble goes off screen.

**Pull request merged**
